name: Generate Documentation
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Generate Documentation
    runs-on: ubuntu-latest
    container: ghcr.io/nextcloud/continuous-integration-client-qt6-doc:client-doc-6.8.0-1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Generate documentation
        run: |
          cd doc
          make html > build.log 2>&1
          if grep WARNING build.log; then
              grep WARNING build.log | awk '{
                      split($0, fields, ":");
                      sub("/__w/desktop/desktop/", "", fields[1]);
                      print "::warning file=" fields[1] ( length(fields[2]) ? ",line=" fields[2] : "" ) ",title=Documentation generation::" substr($0, index($0, fields[4]) + 1)
                  }'

              exit 1
          else
              exit 0
          fi
